/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package me.ryang.files

public class App {

    public static void main(String[] args) {
        Utils.renameAllFiles()
    }
}
